use std::collections::HashSet;

use winit::event::VirtualKeyCode;

#[derive(Default)]
pub struct Keyboard {
    pub keys_pressed: HashSet<VirtualKeyCode>,
    pub keys_just_pressed: HashSet<VirtualKeyCode>,
}

pub fn str_from_key(keycode: &VirtualKeyCode) -> &str {
    match keycode {
        VirtualKeyCode::Key1 => "1" ,
        VirtualKeyCode::Key2 => "2",
        VirtualKeyCode::Key3 => "3",
        VirtualKeyCode::Key4 => "4",
        VirtualKeyCode::Key5 => "5",
        VirtualKeyCode::Key6 => "6",
        VirtualKeyCode::Key7 => "7",
        VirtualKeyCode::Key8 => "8",
        VirtualKeyCode::Key9 => "9",
        VirtualKeyCode::Key0 => "0",
        VirtualKeyCode::A => "A",
        VirtualKeyCode::B => "B",
        VirtualKeyCode::C => "C",
        VirtualKeyCode::D => "D",
        VirtualKeyCode::E => "E",
        VirtualKeyCode::F => "F",
        VirtualKeyCode::G => "G",
        VirtualKeyCode::H => "H",
        VirtualKeyCode::I => "I",
        VirtualKeyCode::J => "J",
        VirtualKeyCode::K => "K",
        VirtualKeyCode::L => "L",
        VirtualKeyCode::M => "M",
        VirtualKeyCode::N => "N",
        VirtualKeyCode::O => "O",
        VirtualKeyCode::P => "P",
        VirtualKeyCode::Q => "Q",
        VirtualKeyCode::R => "R",
        VirtualKeyCode::S => "S",
        VirtualKeyCode::T => "T",
        VirtualKeyCode::U => "U",
        VirtualKeyCode::V => "V",
        VirtualKeyCode::W => "W",
        VirtualKeyCode::X => "X",
        VirtualKeyCode::Y => "Y",
        VirtualKeyCode::Z => "Z",
        VirtualKeyCode::Space => " ",
        VirtualKeyCode::Period => ".",
        VirtualKeyCode::Slash => "/",
        VirtualKeyCode::Backslash => "\\",
        VirtualKeyCode::Left => "Left",
        VirtualKeyCode::Up => "Up",
        VirtualKeyCode::Right => "Right",
        VirtualKeyCode::Down => "Down",
        VirtualKeyCode::Back => "Back",
        VirtualKeyCode::Return => "Enter",
        _ => ""
    }
}

pub fn key_from_str(str: &str) -> Option<VirtualKeyCode> {
    //Only keys that we wanna support within the engine
    //Dont add others just to make sure lua doesn't have full access
    match str {
        "1" => Some(VirtualKeyCode::Key1),
        "2" => Some(VirtualKeyCode::Key2),
        "3" => Some(VirtualKeyCode::Key3),
        "4" => Some(VirtualKeyCode::Key4),
        "5" => Some(VirtualKeyCode::Key5),
        "6" => Some(VirtualKeyCode::Key6),
        "7" => Some(VirtualKeyCode::Key7),
        "8" => Some(VirtualKeyCode::Key8),
        "9" => Some(VirtualKeyCode::Key9),
        "0" => Some(VirtualKeyCode::Key0),
        "A" => Some(VirtualKeyCode::A),
        "B" => Some(VirtualKeyCode::B),
        "C" => Some(VirtualKeyCode::C),
        "D" => Some(VirtualKeyCode::D),
        "E" => Some(VirtualKeyCode::E),
        "F" => Some(VirtualKeyCode::F),
        "G" => Some(VirtualKeyCode::G),
        "H" => Some(VirtualKeyCode::H),
        "I" => Some(VirtualKeyCode::I),
        "J" => Some(VirtualKeyCode::J),
        "K" => Some(VirtualKeyCode::K),
        "L" => Some(VirtualKeyCode::L),
        "M" => Some(VirtualKeyCode::M),
        "N" => Some(VirtualKeyCode::N),
        "O" => Some(VirtualKeyCode::O),
        "P" => Some(VirtualKeyCode::P),
        "Q" => Some(VirtualKeyCode::Q),
        "R" => Some(VirtualKeyCode::R),
        "S" => Some(VirtualKeyCode::S),
        "T" => Some(VirtualKeyCode::T),
        "U" => Some(VirtualKeyCode::U),
        "V" => Some(VirtualKeyCode::V),
        "W" => Some(VirtualKeyCode::W),
        "X" => Some(VirtualKeyCode::X),
        "Y" => Some(VirtualKeyCode::Y),
        "Z" => Some(VirtualKeyCode::Z),
        "Left" => Some(VirtualKeyCode::Left),
        "Up" => Some(VirtualKeyCode::Up),
        "Right" => Some(VirtualKeyCode::Right),
        "Down" => Some(VirtualKeyCode::Down),
        "Back" => Some(VirtualKeyCode::Back),
        "Enter" => Some(VirtualKeyCode::Return),
        "Space" => Some(VirtualKeyCode::Space),
        "Period" => Some(VirtualKeyCode::Period),
        "Slash" => Some(VirtualKeyCode::Slash),
        "Backslash" => Some(VirtualKeyCode::Backslash),
        _ => None,
    }
}
